# Generated by Django 5.0.7 on 2024-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f0', models.FloatField()),
                ('f1', models.FloatField()),
                ('f2', models.FloatField()),
                ('product', models.FloatField(default=99999)),
            ],
        ),
    ]
